/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const FeePaymentRecord = IDL.Record({
  'status' : PaymentStatus,
  'studentName' : IDL.Text,
  'feeTitle' : IDL.Text,
  'recordId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FeeCategory = IDL.Record({
  'title' : IDL.Text,
  'amount' : IDL.Nat,
});
export const HomepageContent = IDL.Record({
  'contactInfo' : IDL.Text,
  'aboutUs' : IDL.Text,
  'tagline' : IDL.Text,
  'learningMethods' : IDL.Text,
  'studentConnection' : IDL.Text,
  'heroText' : IDL.Text,
  'schoolAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFeeCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFeeCategory' : IDL.Func([IDL.Text], [], []),
  'getAllPaymentRecords' : IDL.Func([], [IDL.Vec(FeePaymentRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeeCategories' : IDL.Func([], [IDL.Vec(FeeCategory)], ['query']),
  'getHomepageContent' : IDL.Func([], [HomepageContent], ['query']),
  'getPaymentRecord' : IDL.Func([IDL.Nat], [FeePaymentRecord], ['query']),
  'getStudentRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FeePaymentRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'registerOwner' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'updateFeeCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateHomepageContent' : IDL.Func([HomepageContent], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const FeePaymentRecord = IDL.Record({
    'status' : PaymentStatus,
    'studentName' : IDL.Text,
    'feeTitle' : IDL.Text,
    'recordId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FeeCategory = IDL.Record({ 'title' : IDL.Text, 'amount' : IDL.Nat });
  const HomepageContent = IDL.Record({
    'contactInfo' : IDL.Text,
    'aboutUs' : IDL.Text,
    'tagline' : IDL.Text,
    'learningMethods' : IDL.Text,
    'studentConnection' : IDL.Text,
    'heroText' : IDL.Text,
    'schoolAddress' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFeeCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFeeCategory' : IDL.Func([IDL.Text], [], []),
    'getAllPaymentRecords' : IDL.Func(
        [],
        [IDL.Vec(FeePaymentRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeeCategories' : IDL.Func([], [IDL.Vec(FeeCategory)], ['query']),
    'getHomepageContent' : IDL.Func([], [HomepageContent], ['query']),
    'getPaymentRecord' : IDL.Func([IDL.Nat], [FeePaymentRecord], ['query']),
    'getStudentRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeePaymentRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'registerOwner' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'updateFeeCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateHomepageContent' : IDL.Func([HomepageContent], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };