/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FeeCategory { 'title' : string, 'amount' : bigint }
export interface FeePaymentRecord {
  'status' : PaymentStatus,
  'studentName' : string,
  'feeTitle' : string,
  'recordId' : bigint,
  'amount' : bigint,
}
export interface HomepageContent {
  'contactInfo' : string,
  'aboutUs' : string,
  'tagline' : string,
  'learningMethods' : string,
  'studentConnection' : string,
  'heroText' : string,
  'schoolAddress' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'unpaid' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFeeCategory' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFeeCategory' : ActorMethod<[string], undefined>,
  'getAllPaymentRecords' : ActorMethod<[], Array<FeePaymentRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeeCategories' : ActorMethod<[], Array<FeeCategory>>,
  'getHomepageContent' : ActorMethod<[], HomepageContent>,
  'getPaymentRecord' : ActorMethod<[bigint], FeePaymentRecord>,
  'getStudentRecords' : ActorMethod<[string], Array<FeePaymentRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasOwner' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOwner' : ActorMethod<[], boolean>,
  'registerOwner' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFeePayment' : ActorMethod<[string, string, bigint], bigint>,
  'updateFeeCategory' : ActorMethod<[string, bigint], undefined>,
  'updateHomepageContent' : ActorMethod<[HomepageContent], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];