/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmissionsContent = IDL.Record({
  'faq' : IDL.Text,
  'applicationSteps' : IDL.Text,
  'portalLink' : IDL.Text,
  'documents' : IDL.Text,
  'eligibility' : IDL.Text,
  'process' : IDL.Text,
});
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
  'phone' : IDL.Text,
});
export const FeeCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Photo = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'caption' : IDL.Text,
});
export const HeroStats = IDL.Record({
  'facultyCount' : IDL.Nat,
  'yearsOfExcellence' : IDL.Nat,
  'studentsEnrolled' : IDL.Nat,
});
export const SchoolHighlights = IDL.Record({
  'highlight1' : IDL.Text,
  'highlight2' : IDL.Text,
  'highlight3' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'feedback' : IDL.Text,
});
export const HomeHeroSection = IDL.Record({
  'tagline' : IDL.Text,
  'heroStats' : HeroStats,
  'address' : IDL.Text,
  'schoolHighlights' : SchoolHighlights,
  'testimonials' : IDL.Vec(Testimonial),
  'schoolName' : IDL.Text,
});
export const SchoolInfo = IDL.Record({
  'instagramLink' : IDL.Text,
  'twitterLink' : IDL.Text,
  'adminContactInfo' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'principalName' : IDL.Text,
  'facebookLink' : IDL.Text,
  'emailAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'schoolName' : IDL.Text,
});
export const ThemeSettings = IDL.Record({
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'fontChoice' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addFeeCategory' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addPhoto' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteFeeCategory' : IDL.Func([IDL.Nat], [], []),
  'deletePhoto' : IDL.Func([IDL.Nat], [], []),
  'getAdmissionsContent' : IDL.Func([], [AdmissionsContent], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getFeeCategories' : IDL.Func([], [IDL.Vec(FeeCategory)], ['query']),
  'getGallery' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getHomeHeroSection' : IDL.Func([], [HomeHeroSection], ['query']),
  'getSchoolInfo' : IDL.Func([], [SchoolInfo], ['query']),
  'getThemeSettings' : IDL.Func([], [ThemeSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateAdmissionsContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateFeeCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'updateHomeHeroSection' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        HeroStats,
        SchoolHighlights,
        IDL.Vec(Testimonial),
      ],
      [],
      [],
    ),
  'updateSchoolInfo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateThemeSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmissionsContent = IDL.Record({
    'faq' : IDL.Text,
    'applicationSteps' : IDL.Text,
    'portalLink' : IDL.Text,
    'documents' : IDL.Text,
    'eligibility' : IDL.Text,
    'process' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const FeeCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Photo = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'caption' : IDL.Text,
  });
  const HeroStats = IDL.Record({
    'facultyCount' : IDL.Nat,
    'yearsOfExcellence' : IDL.Nat,
    'studentsEnrolled' : IDL.Nat,
  });
  const SchoolHighlights = IDL.Record({
    'highlight1' : IDL.Text,
    'highlight2' : IDL.Text,
    'highlight3' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'feedback' : IDL.Text,
  });
  const HomeHeroSection = IDL.Record({
    'tagline' : IDL.Text,
    'heroStats' : HeroStats,
    'address' : IDL.Text,
    'schoolHighlights' : SchoolHighlights,
    'testimonials' : IDL.Vec(Testimonial),
    'schoolName' : IDL.Text,
  });
  const SchoolInfo = IDL.Record({
    'instagramLink' : IDL.Text,
    'twitterLink' : IDL.Text,
    'adminContactInfo' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'principalName' : IDL.Text,
    'facebookLink' : IDL.Text,
    'emailAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  const ThemeSettings = IDL.Record({
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'fontChoice' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addFeeCategory' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addPhoto' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteFeeCategory' : IDL.Func([IDL.Nat], [], []),
    'deletePhoto' : IDL.Func([IDL.Nat], [], []),
    'getAdmissionsContent' : IDL.Func([], [AdmissionsContent], ['query']),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getFeeCategories' : IDL.Func([], [IDL.Vec(FeeCategory)], ['query']),
    'getGallery' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getHomeHeroSection' : IDL.Func([], [HomeHeroSection], ['query']),
    'getSchoolInfo' : IDL.Func([], [SchoolInfo], ['query']),
    'getThemeSettings' : IDL.Func([], [ThemeSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateAdmissionsContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateFeeCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'updateHomeHeroSection' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          HeroStats,
          SchoolHighlights,
          IDL.Vec(Testimonial),
        ],
        [],
        [],
      ),
    'updateSchoolInfo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateThemeSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };